In [1]:
import pandas as pd

In [ ]:
data=pd.read_csv("./Dataset/covid_19_india.csv")

In [6]:
data

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
0,1,2020-01-30,6:00 PM,Kerala,1,0,0,0,1
1,2,2020-01-31,6:00 PM,Kerala,1,0,0,0,1
2,3,2020-02-01,6:00 PM,Kerala,2,0,0,0,2
3,4,2020-02-02,6:00 PM,Kerala,3,0,0,0,3
4,5,2020-02-03,6:00 PM,Kerala,3,0,0,0,3
...,...,...,...,...,...,...,...,...,...
18105,18106,2021-08-11,8:00 AM,Telangana,-,-,638410,3831,650353
18106,18107,2021-08-11,8:00 AM,Tripura,-,-,77811,773,80660
18107,18108,2021-08-11,8:00 AM,Uttarakhand,-,-,334650,7368,342462
18108,18109,2021-08-11,8:00 AM,Uttar Pradesh,-,-,1685492,22775,1708812
18109,18110,2021-08-11,8:00 AM,West Bengal,-,-,1506532,18252,1534999

In [8]:
data.head()

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
0,1,2020-01-30,6:00 PM,Kerala,1,0,0,0,1
1,2,2020-01-31,6:00 PM,Kerala,1,0,0,0,1
2,3,2020-02-01,6:00 PM,Kerala,2,0,0,0,2
3,4,2020-02-02,6:00 PM,Kerala,3,0,0,0,3
4,5,2020-02-03,6:00 PM,Kerala,3,0,0,0,3

In [9]:
data.tail()

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
18105,18106,2021-08-11,8:00 AM,Telangana,-,-,638410,3831,650353
18106,18107,2021-08-11,8:00 AM,Tripura,-,-,77811,773,80660
18107,18108,2021-08-11,8:00 AM,Uttarakhand,-,-,334650,7368,342462
18108,18109,2021-08-11,8:00 AM,Uttar Pradesh,-,-,1685492,22775,1708812
18109,18110,2021-08-11,8:00 AM,West Bengal,-,-,1506532,18252,1534999

In [10]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 18110 entries, 0 to 18109
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Sno                       18110 non-null  int64
 1   Date                      18110 non-null  str
 2   Time                      18110 non-null  str
 3   State/UnionTerritory      18110 non-null  str
 4   ConfirmedIndianNational   18110 non-null  str
 5   ConfirmedForeignNational  18110 non-null  str
 6   Cured                     18110 non-null  int64
 7   Deaths                    18110 non-null  int64
 8   Confirmed                 18110 non-null  int64
dtypes: int64(4), str(5)
memory usage: 1.2 MB

In [13]:
data.describe()

                Sno         Cured         Deaths     Confirmed
count  18110.000000  1.811000e+04   18110.000000  1.811000e+04
mean    9055.500000  2.786375e+05    4052.402264  3.010314e+05
std     5228.051023  6.148909e+05   10919.076411  6.561489e+05
min        1.000000  0.000000e+00       0.000000  0.000000e+00
25%     4528.250000  3.360250e+03      32.000000  4.376750e+03
50%     9055.500000  3.336400e+04     588.000000  3.977350e+04
75%    13582.750000  2.788698e+05    3643.750000  3.001498e+05
max    18110.000000  6.159676e+06  134201.000000  6.363442e+06

In [15]:
df=pd.DataFrame(data)

In [16]:
df

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
0,1,2020-01-30,6:00 PM,Kerala,1,0,0,0,1
1,2,2020-01-31,6:00 PM,Kerala,1,0,0,0,1
2,3,2020-02-01,6:00 PM,Kerala,2,0,0,0,2
3,4,2020-02-02,6:00 PM,Kerala,3,0,0,0,3
4,5,2020-02-03,6:00 PM,Kerala,3,0,0,0,3
...,...,...,...,...,...,...,...,...,...
18105,18106,2021-08-11,8:00 AM,Telangana,-,-,638410,3831,650353
18106,18107,2021-08-11,8:00 AM,Tripura,-,-,77811,773,80660
18107,18108,2021-08-11,8:00 AM,Uttarakhand,-,-,334650,7368,342462
18108,18109,2021-08-11,8:00 AM,Uttar Pradesh,-,-,1685492,22775,1708812
18109,18110,2021-08-11,8:00 AM,West Bengal,-,-,1506532,18252,1534999

In [20]:
df[['Sno','Date','Cured']]

         Sno        Date    Cured
0          1  2020-01-30        0
1          2  2020-01-31        0
2          3  2020-02-01        0
3          4  2020-02-02        0
4          5  2020-02-03        0
...      ...         ...      ...
18105  18106  2021-08-11   638410
18106  18107  2021-08-11    77811
18107  18108  2021-08-11   334650
18108  18109  2021-08-11  1685492
18109  18110  2021-08-11  1506532

[18110 rows x 3 columns]

In [22]:
df.loc[0]
df.loc[18000]

Sno                                 18001
Date                           2021-08-08
Time                              8:00 AM
State/UnionTerritory        Uttar Pradesh
ConfirmedIndianNational                 -
ConfirmedForeignNational                -
Cured                             1685357
Deaths                              22773
Confirmed                         1708716
Name: 18000, dtype: object

In [23]:
df.loc[0:1000,"Sno"]

0          1
1          2
2          3
3          4
4          5
        ...
996      997
997      998
998      999
999     1000
1000    1001
Name: Sno, Length: 1001, dtype: int64

In [26]:
df.iloc[0:2,0:2]

   Sno        Date
0    1  2020-01-30
1    2  2020-01-31

In [27]:
df["Cases On Mars"]=0

In [28]:
df

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed,Cases On Mars
0,1,2020-01-30,6:00 PM,Kerala,1,0,0,0,1,0
1,2,2020-01-31,6:00 PM,Kerala,1,0,0,0,1,0
2,3,2020-02-01,6:00 PM,Kerala,2,0,0,0,2,0
3,4,2020-02-02,6:00 PM,Kerala,3,0,0,0,3,0
4,5,2020-02-03,6:00 PM,Kerala,3,0,0,0,3,0
...,...,...,...,...,...,...,...,...,...,...
18105,18106,2021-08-11,8:00 AM,Telangana,-,-,638410,3831,650353,0
18106,18107,2021-08-11,8:00 AM,Tripura,-,-,77811,773,80660,0
18107,18108,2021-08-11,8:00 AM,Uttarakhand,-,-,334650,7368,342462,0
18108,18109,2021-08-11,8:00 AM,Uttar Pradesh,-,-,1685492,22775,1708812,0
18109,18110,2021-08-11,8:00 AM,West Bengal,-,-,1506532,18252,1534999,0

In [29]:
df.drop("Confirmed",axis=1,inplace=False)

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Cases On Mars
0,1,2020-01-30,6:00 PM,Kerala,1,0,0,0,0
1,2,2020-01-31,6:00 PM,Kerala,1,0,0,0,0
2,3,2020-02-01,6:00 PM,Kerala,2,0,0,0,0
3,4,2020-02-02,6:00 PM,Kerala,3,0,0,0,0
4,5,2020-02-03,6:00 PM,Kerala,3,0,0,0,0
...,...,...,...,...,...,...,...,...,...
18105,18106,2021-08-11,8:00 AM,Telangana,-,-,638410,3831,0
18106,18107,2021-08-11,8:00 AM,Tripura,-,-,77811,773,0
18107,18108,2021-08-11,8:00 AM,Uttarakhand,-,-,334650,7368,0
18108,18109,2021-08-11,8:00 AM,Uttar Pradesh,-,-,1685492,22775,0
18109,18110,2021-08-11,8:00 AM,West Bengal,-,-,1506532,18252,0

In [30]:
df

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed,Cases On Mars
0,1,2020-01-30,6:00 PM,Kerala,1,0,0,0,1,0
1,2,2020-01-31,6:00 PM,Kerala,1,0,0,0,1,0
2,3,2020-02-01,6:00 PM,Kerala,2,0,0,0,2,0
3,4,2020-02-02,6:00 PM,Kerala,3,0,0,0,3,0
4,5,2020-02-03,6:00 PM,Kerala,3,0,0,0,3,0
...,...,...,...,...,...,...,...,...,...,...
18105,18106,2021-08-11,8:00 AM,Telangana,-,-,638410,3831,650353,0
18106,18107,2021-08-11,8:00 AM,Tripura,-,-,77811,773,80660,0
18107,18108,2021-08-11,8:00 AM,Uttarakhand,-,-,334650,7368,342462,0
18108,18109,2021-08-11,8:00 AM,Uttar Pradesh,-,-,1685492,22775,1708812,0
18109,18110,2021-08-11,8:00 AM,West Bengal,-,-,1506532,18252,1534999,0

In [31]:
df.drop("Confirmed",axis=1,inplace=True)

In [32]:
df

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Cases On Mars
0,1,2020-01-30,6:00 PM,Kerala,1,0,0,0,0
1,2,2020-01-31,6:00 PM,Kerala,1,0,0,0,0
2,3,2020-02-01,6:00 PM,Kerala,2,0,0,0,0
3,4,2020-02-02,6:00 PM,Kerala,3,0,0,0,0
4,5,2020-02-03,6:00 PM,Kerala,3,0,0,0,0
...,...,...,...,...,...,...,...,...,...
18105,18106,2021-08-11,8:00 AM,Telangana,-,-,638410,3831,0
18106,18107,2021-08-11,8:00 AM,Tripura,-,-,77811,773,0
18107,18108,2021-08-11,8:00 AM,Uttarakhand,-,-,334650,7368,0
18108,18109,2021-08-11,8:00 AM,Uttar Pradesh,-,-,1685492,22775,0
18109,18110,2021-08-11,8:00 AM,West Bengal,-,-,1506532,18252,0

In [33]:
df.rename(columns={"Sno":"DayNo"})

,DayNo,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Cases On Mars
0,1,2020-01-30,6:00 PM,Kerala,1,0,0,0,0
1,2,2020-01-31,6:00 PM,Kerala,1,0,0,0,0
2,3,2020-02-01,6:00 PM,Kerala,2,0,0,0,0
3,4,2020-02-02,6:00 PM,Kerala,3,0,0,0,0
4,5,2020-02-03,6:00 PM,Kerala,3,0,0,0,0
...,...,...,...,...,...,...,...,...,...
18105,18106,2021-08-11,8:00 AM,Telangana,-,-,638410,3831,0
18106,18107,2021-08-11,8:00 AM,Tripura,-,-,77811,773,0
18107,18108,2021-08-11,8:00 AM,Uttarakhand,-,-,334650,7368,0
18108,18109,2021-08-11,8:00 AM,Uttar Pradesh,-,-,1685492,22775,0
18109,18110,2021-08-11,8:00 AM,West Bengal,-,-,1506532,18252,0

In [34]:
df

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Cases On Mars
0,1,2020-01-30,6:00 PM,Kerala,1,0,0,0,0
1,2,2020-01-31,6:00 PM,Kerala,1,0,0,0,0
2,3,2020-02-01,6:00 PM,Kerala,2,0,0,0,0
3,4,2020-02-02,6:00 PM,Kerala,3,0,0,0,0
4,5,2020-02-03,6:00 PM,Kerala,3,0,0,0,0
...,...,...,...,...,...,...,...,...,...
18105,18106,2021-08-11,8:00 AM,Telangana,-,-,638410,3831,0
18106,18107,2021-08-11,8:00 AM,Tripura,-,-,77811,773,0
18107,18108,2021-08-11,8:00 AM,Uttarakhand,-,-,334650,7368,0
18108,18109,2021-08-11,8:00 AM,Uttar Pradesh,-,-,1685492,22775,0
18109,18110,2021-08-11,8:00 AM,West Bengal,-,-,1506532,18252,0

In [36]:
df.rename(columns={"Sno":"DayNo"},inplace=True)

In [37]:
df

,DayNo,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Cases On Mars
0,1,2020-01-30,6:00 PM,Kerala,1,0,0,0,0
1,2,2020-01-31,6:00 PM,Kerala,1,0,0,0,0
2,3,2020-02-01,6:00 PM,Kerala,2,0,0,0,0
3,4,2020-02-02,6:00 PM,Kerala,3,0,0,0,0
4,5,2020-02-03,6:00 PM,Kerala,3,0,0,0,0
...,...,...,...,...,...,...,...,...,...
18105,18106,2021-08-11,8:00 AM,Telangana,-,-,638410,3831,0
18106,18107,2021-08-11,8:00 AM,Tripura,-,-,77811,773,0
18107,18108,2021-08-11,8:00 AM,Uttarakhand,-,-,334650,7368,0
18108,18109,2021-08-11,8:00 AM,Uttar Pradesh,-,-,1685492,22775,0
18109,18110,2021-08-11,8:00 AM,West Bengal,-,-,1506532,18252,0

In [38]:
df.sort_values(by="Deaths",ascending=False)

,DayNo,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Cases On Mars
18094,18095,2021-08-11,8:00 AM,Maharashtra,-,-,6159676,134201,0
18058,18059,2021-08-10,8:00 AM,Maharashtra,-,-,6151956,134064,0
18022,18023,2021-08-09,8:00 AM,Maharashtra,-,-,6144388,133996,0
17986,17987,2021-08-08,8:00 AM,Maharashtra,-,-,6139493,133845,0
17950,17951,2021-08-07,8:00 AM,Maharashtra,-,-,6130137,133717,0
...,...,...,...,...,...,...,...,...,...
20,21,2020-02-19,6:00 PM,Kerala,3,0,0,0,0
19,20,2020-02-18,6:00 PM,Kerala,3,0,0,0,0
18,19,2020-02-17,6:00 PM,Kerala,3,0,0,0,0
17,18,2020-02-16,6:00 PM,Kerala,3,0,0,0,0
16,17,2020-02-15,6:00 PM,Kerala,3,0,0,0,0

In [39]:
print(df[df["Cured"]>df["Deaths"]])

       DayNo        Date     Time State/UnionTerritory  \
37        38  2020-03-03  6:00 PM               Kerala
40        41  2020-03-04  6:00 PM               Kerala
47        48  2020-03-05  6:00 PM               Kerala
53        54  2020-03-06  6:00 PM               Kerala
57        58  2020-03-07  6:00 PM               Kerala
...      ...         ...      ...                  ...
18105  18106  2021-08-11  8:00 AM            Telangana
18106  18107  2021-08-11  8:00 AM              Tripura
18107  18108  2021-08-11  8:00 AM          Uttarakhand
18108  18109  2021-08-11  8:00 AM        Uttar Pradesh
18109  18110  2021-08-11  8:00 AM          West Bengal

      ConfirmedIndianNational ConfirmedForeignNational    Cured  Deaths  \
37                          3                        0        3       0
40                          3                        0        3       0
47                          3                        0        3       0
53                          3                        0        3       0
57                          3                        0        3       0
...                       ...                      ...      ...     ...
18105                       -                        -   638410    3831
18106                       -                        -    77811     773
18107                       -                        -   334650    7368
18108                       -                        -  1685492   22775
18109                       -                        -  1506532   18252

       Cases On Mars
37                 0
40                 0
47                 0
53                 0
57                 0
...              ...
18105              0
18106              0
18107              0
18108              0
18109              0

[17327 rows x 9 columns]

In [43]:
print(df[df["Cured"]>df["ConfirmedIndianNational"]])     # Will not work because Cured is in integer data type where as ConfirmedIndianNational is in string datatype

TypeError: '<' not supported between instances of 'str' and 'int'

In [44]:
df.isnull()

,DayNo,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Cases On Mars
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
18105,False,False,False,False,False,False,False,False,False
18106,False,False,False,False,False,False,False,False,False
18107,False,False,False,False,False,False,False,False,False
18108,False,False,False,False,False,False,False,False,False
18109,False,False,False,False,False,False,False,False,False

In [45]:
df.isnull().sum()

DayNo                       0
Date                        0
Time                        0
State/UnionTerritory        0
ConfirmedIndianNational     0
ConfirmedForeignNational    0
Cured                       0
Deaths                      0
Cases On Mars               0
dtype: int64

In [46]:
df["Cases On Mars"].fillna(df['ConfirmedForeignNational'])

0        0
1        0
2        0
3        0
4        0
        ..
18105    0
18106    0
18107    0
18108    0
18109    0
Name: Cases On Mars, Length: 18110, dtype: int64

In [52]:
df["Cases on Jupiter"].fillna(df["ConfirmedForeignNational"])

KeyError: 'Cases on Jupiter'

In [61]:
print(f"Total cases: {df.Cured.tail(1) + df.Deaths.tail(1)}")

Total cases: 18109    1524784
dtype: int64

In [72]:
print(df.groupby("State/UnionTerritory")[["Cured","Deaths"]])

<pandas.api.typing.DataFrameGroupBy object at 0x000001B6C29C5C50>

In [69]:
df.describe()

              DayNo         Cured         Deaths  Cases On Mars
count  18110.000000  1.811000e+04   18110.000000        18110.0
mean    9055.500000  2.786375e+05    4052.402264            0.0
std     5228.051023  6.148909e+05   10919.076411            0.0
min        1.000000  0.000000e+00       0.000000            0.0
25%     4528.250000  3.360250e+03      32.000000            0.0
50%     9055.500000  3.336400e+04     588.000000            0.0
75%    13582.750000  2.788698e+05    3643.750000            0.0
max    18110.000000  6.159676e+06  134201.000000            0.0

In [66]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18110 entries, 0 to 18109
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   DayNo                     18110 non-null  int64
 1   Date                      18110 non-null  str
 2   Time                      18110 non-null  str
 3   State/UnionTerritory      18110 non-null  str
 4   ConfirmedIndianNational   18110 non-null  str
 5   ConfirmedForeignNational  18110 non-null  str
 6   Cured                     18110 non-null  int64
 7   Deaths                    18110 non-null  int64
 8   Cases On Mars             18110 non-null  int64
dtypes: int64(4), str(5)
memory usage: 1.2 MB

In [70]:
df

,DayNo,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Cases On Mars
0,1,2020-01-30,6:00 PM,Kerala,1,0,0,0,0
1,2,2020-01-31,6:00 PM,Kerala,1,0,0,0,0
2,3,2020-02-01,6:00 PM,Kerala,2,0,0,0,0
3,4,2020-02-02,6:00 PM,Kerala,3,0,0,0,0
4,5,2020-02-03,6:00 PM,Kerala,3,0,0,0,0
...,...,...,...,...,...,...,...,...,...
18105,18106,2021-08-11,8:00 AM,Telangana,-,-,638410,3831,0
18106,18107,2021-08-11,8:00 AM,Tripura,-,-,77811,773,0
18107,18108,2021-08-11,8:00 AM,Uttarakhand,-,-,334650,7368,0
18108,18109,2021-08-11,8:00 AM,Uttar Pradesh,-,-,1685492,22775,0
18109,18110,2021-08-11,8:00 AM,West Bengal,-,-,1506532,18252,0

In [73]:
df['State/UnionTerritory'].unique()

<StringArray>
[                                  'Kerala',
                                'Telengana',
                                    'Delhi',
                                'Rajasthan',
                            'Uttar Pradesh',
                                  'Haryana',
                                   'Ladakh',
                               'Tamil Nadu',
                                'Karnataka',
                              'Maharashtra',
                                   'Punjab',
                        'Jammu and Kashmir',
                           'Andhra Pradesh',
                              'Uttarakhand',
                                   'Odisha',
                               'Puducherry',
                              'West Bengal',
                             'Chhattisgarh',
                               'Chandigarh',
                                  'Gujarat',
                         'Himachal Pradesh',
                           'Madhya Pradesh',
                                    'Bihar',
                                  'Manipur',
                                  'Mizoram',
              'Andaman and Nicobar Islands',
                                      'Goa',
                               'Unassigned',
                                    'Assam',
                                'Jharkhand',
                        'Arunachal Pradesh',
                                  'Tripura',
                                 'Nagaland',
                                'Meghalaya',
 'Dadra and Nagar Haveli and Daman and Diu',
         'Cases being reassigned to states',
                                   'Sikkim',
                              'Daman & Diu',
                              'Lakshadweep',
                                'Telangana',
                   'Dadra and Nagar Haveli',
                                'Bihar****',
                        'Madhya Pradesh***',
                        'Himanchal Pradesh',
                               'Karanataka',
                           'Maharashtra***']
Length: 46, dtype: str

In [74]:
df['State/UnionTerritory'].nunique()

46