In [ ]:
# pandas :-
# pip install pandas
# python -m pip install pandas
# py -m pip install pandas

In [ ]:
import pandas as pd

creating dataframe

In [2]:
data={
    "Name":["kartik","yukti","gagan","mayur"],
    "age":[90,89,87,100],
    "salary":[1,2,3,4]
}

In [3]:
df=pd.DataFrame(data)
print(df)

     Name  age  salary
0  kartik   90       1
1   yukti   89       2
2   gagan   87       3
3   mayur  100       4

In [5]:
df.head(2)

     Name  age  salary
0  kartik   90       1
1   yukti   89       2

In [7]:
df.tail(2)

    Name  age  salary
2  gagan   87       3
3  mayur  100       4

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   age     4 non-null      int64
 2   salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [9]:
df.describe()

              age    salary
count    4.000000  4.000000
mean    91.500000  2.500000
std      5.802298  1.290994
min     87.000000  1.000000
25%     88.500000  1.750000
50%     89.500000  2.500000
75%     92.500000  3.250000
max    100.000000  4.000000

selecting data

In [10]:
print(df["Name"])

0    kartik
1     yukti
2     gagan
3     mayur
Name: Name, dtype: object

In [11]:
print(df[["Name","salary"]])

     Name  salary
0  kartik       1
1   yukti       2
2   gagan       3
3   mayur       4

loc and iloc function

In [12]:
print(df.loc[0])

Name      kartik
age           90
salary         1
Name: 0, dtype: object

In [13]:
print(df.loc[0:2,"Name"])

0    kartik
1     yukti
2     gagan
Name: Name, dtype: object

In [17]:
print(df.iloc[0:2,0:2])

     Name  age
0  kartik   90
1   yukti   89

adding new column

In [19]:
df["Bonus"]=[0.5,0.6,0.7,0.8]

In [20]:
print(df)

     Name  age  salary  Bonus
0  kartik   90       1    0.5
1   yukti   89       2    0.6
2   gagan   87       3    0.7
3   mayur  100       4    0.8

Dropping column

In [21]:
df.drop("salary",axis=1, inplace=True)

In [22]:
df

     Name  age  Bonus
0  kartik   90    0.5
1   yukti   89    0.6
2   gagan   87    0.7
3   mayur  100    0.8

Renaming columns

In [23]:
df.rename(columns={"Name":"Student_name"},inplace=True)

In [24]:
df

  Student_name  age  Bonus
0       kartik   90    0.5
1        yukti   89    0.6
2        gagan   87    0.7
3        mayur  100    0.8

Sorting Data

In [27]:
df.sort_values(by="age",ascending=False)

  Student_name  age  Bonus
3        mayur  100    0.8
0       kartik   90    0.5
1        yukti   89    0.6
2        gagan   87    0.7

Filter data

In [28]:
print(df[df["age"]>90])

  Student_name  age  Bonus
3        mayur  100    0.8

Handling missing values

In [29]:
df.isnull()

   Student_name    age  Bonus
0         False  False  False
1         False  False  False
2         False  False  False
3         False  False  False

In [30]:
df.isnull().sum()

Student_name    0
age             0
Bonus           0
dtype: int64

fillna values

In [36]:
df["age"].fillna(df["age"].mean(),inplace=True)

/tmp/ipykernel_719/613402698.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["age"].fillna(df["age"].mean(),inplace=True)

mathematical function

In [37]:
df["Bonus"].sum()

np.float64(2.6)

In [38]:
df["Bonus"].mean()

np.float64(0.65)

In [39]:
df["Bonus"].max()

0.8

In [40]:
df["Bonus"].min()

0.5

In [41]:
df["Bonus"].count()

np.int64(4)

Grouping data

In [44]:
data={
    "Department":["HR","IT","IT","HR"],
    "Salary":[20000,30000,40000,50000]
    }
df=pd.DataFrame(data)
print(df.groupby("Department")["Salary"].mean())

Department
HR    35000.0
IT    35000.0
Name: Salary, dtype: float64

Unique Values

In [45]:
print(df['Department'].unique())

['HR' 'IT']

In [46]:
print(df['Department'].nunique())

2

Reading File

In [ ]:
df=pd.read_csv("file_path")

In [ ]:
from google.colab import files, drive

In [52]:
uploaded=files.upload()

Saving covid_19_india.csv to covid_19_india.csv

In [53]:
df=pd.read_csv("covid_19_india.csv")

In [54]:
df

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
0,1,2020-01-30,6:00 PM,Kerala,1,0,0,0,1
1,2,2020-01-31,6:00 PM,Kerala,1,0,0,0,1
2,3,2020-02-01,6:00 PM,Kerala,2,0,0,0,2
3,4,2020-02-02,6:00 PM,Kerala,3,0,0,0,3
4,5,2020-02-03,6:00 PM,Kerala,3,0,0,0,3
...,...,...,...,...,...,...,...,...,...
18105,18106,2021-08-11,8:00 AM,Telangana,-,-,638410,3831,650353
18106,18107,2021-08-11,8:00 AM,Tripura,-,-,77811,773,80660
18107,18108,2021-08-11,8:00 AM,Uttarakhand,-,-,334650,7368,342462
18108,18109,2021-08-11,8:00 AM,Uttar Pradesh,-,-,1685492,22775,1708812
18109,18110,2021-08-11,8:00 AM,West Bengal,-,-,1506532,18252,1534999

In [55]:
df.head()

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
0,1,2020-01-30,6:00 PM,Kerala,1,0,0,0,1
1,2,2020-01-31,6:00 PM,Kerala,1,0,0,0,1
2,3,2020-02-01,6:00 PM,Kerala,2,0,0,0,2
3,4,2020-02-02,6:00 PM,Kerala,3,0,0,0,3
4,5,2020-02-03,6:00 PM,Kerala,3,0,0,0,3

In [56]:
df.tail()

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
18105,18106,2021-08-11,8:00 AM,Telangana,-,-,638410,3831,650353
18106,18107,2021-08-11,8:00 AM,Tripura,-,-,77811,773,80660
18107,18108,2021-08-11,8:00 AM,Uttarakhand,-,-,334650,7368,342462
18108,18109,2021-08-11,8:00 AM,Uttar Pradesh,-,-,1685492,22775,1708812
18109,18110,2021-08-11,8:00 AM,West Bengal,-,-,1506532,18252,1534999

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18110 entries, 0 to 18109
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Sno                       18110 non-null  int64
 1   Date                      18110 non-null  object
 2   Time                      18110 non-null  object
 3   State/UnionTerritory      18110 non-null  object
 4   ConfirmedIndianNational   18110 non-null  object
 5   ConfirmedForeignNational  18110 non-null  object
 6   Cured                     18110 non-null  int64
 7   Deaths                    18110 non-null  int64
 8   Confirmed                 18110 non-null  int64
dtypes: int64(4), object(5)
memory usage: 1.2+ MB

In [58]:
df.describe()

                Sno         Cured         Deaths     Confirmed
count  18110.000000  1.811000e+04   18110.000000  1.811000e+04
mean    9055.500000  2.786375e+05    4052.402264  3.010314e+05
std     5228.051023  6.148909e+05   10919.076411  6.561489e+05
min        1.000000  0.000000e+00       0.000000  0.000000e+00
25%     4528.250000  3.360250e+03      32.000000  4.376750e+03
50%     9055.500000  3.336400e+04     588.000000  3.977350e+04
75%    13582.750000  2.788698e+05    3643.750000  3.001498e+05
max    18110.000000  6.159676e+06  134201.000000  6.363442e+06